name: CI

on:
  push:
    branches:
    - main
    - 2.x.x
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    paths:
    - '**.swift'
    - '**.yml'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.9'
          - 'swiftlang/swift:nightly-5.10-jammy'
    
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        swift test
